services:
  traefik:
    image: traefik:v3
    container_name: vinegrape-traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - app-net

  backend:
    build:
      context: ./bekend
      dockerfile: Dockerfile
    container_name: vinegrape-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - backend-static:/app/static
      - backend-data:/app/data
    networks:
      - app-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`api.vinegrape.ru`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8000

  frontend:
    build:
      context: ./frontend/sait-frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: https://api.vinegrape.ru
    container_name: vinegrape-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`vinegrape.ru`)
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.routers.front.tls.certresolver=letsencrypt
      - traefik.http.services.front.loadbalancer.server.port=80

networks:
  app-net:
    driver: bridge

volumes:
  backend-static:
  backend-data:
